2024-06-19 19:13:58,669 INFO    MainThread:14913 [wandb_setup.py:_flush():76] Current SDK version is 0.17.2
2024-06-19 19:13:58,669 INFO    MainThread:14913 [wandb_setup.py:_flush():76] Configure stats pid to 14913
2024-06-19 19:13:58,669 INFO    MainThread:14913 [wandb_setup.py:_flush():76] Loading settings from /home/mdr317/.config/wandb/settings
2024-06-19 19:13:58,669 INFO    MainThread:14913 [wandb_setup.py:_flush():76] Loading settings from /var/scratch/mdr317/thesis/wandb/settings
2024-06-19 19:13:58,669 INFO    MainThread:14913 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-19 19:13:58,670 INFO    MainThread:14913 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-19 19:13:58,670 INFO    MainThread:14913 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'MainVIT.py', 'program_abspath': '/var/scratch/mdr317/thesis/MainVIT.py', 'program': '/var/scratch/mdr317/thesis/MainVIT.py'}
2024-06-19 19:13:58,670 INFO    MainThread:14913 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-19 19:13:58,670 INFO    MainThread:14913 [wandb_init.py:_log_setup():520] Logging user logs to /var/scratch/mdr317/thesis/wandb/run-20240619_191358-yxlp69ta/logs/debug.log
2024-06-19 19:13:58,670 INFO    MainThread:14913 [wandb_init.py:_log_setup():521] Logging internal logs to /var/scratch/mdr317/thesis/wandb/run-20240619_191358-yxlp69ta/logs/debug-internal.log
2024-06-19 19:13:58,670 INFO    MainThread:14913 [wandb_init.py:init():560] calling init triggers
2024-06-19 19:13:58,670 INFO    MainThread:14913 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-06-19 19:13:58,670 INFO    MainThread:14913 [wandb_init.py:init():610] starting backend
2024-06-19 19:13:58,670 INFO    MainThread:14913 [wandb_init.py:init():614] setting up manager
2024-06-19 19:13:58,678 INFO    MainThread:14913 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-06-19 19:13:58,680 INFO    MainThread:14913 [wandb_init.py:init():622] backend started and connected
2024-06-19 19:13:58,696 INFO    MainThread:14913 [wandb_init.py:init():711] updated telemetry
2024-06-19 19:13:58,708 INFO    MainThread:14913 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-19 19:13:58,984 ERROR   MainThread:14913 [wandb_init.py:init():770] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-06-19 19:13:58,984 ERROR   MainThread:14913 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "/var/scratch/mdr317/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
           ^^^^^^^^^
  File "/var/scratch/mdr317/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-06-19 19:14:00,101 WARNING MsgRouterThr:14913 [router.py:message_loop():77] message_loop has been closed
